- name: "Populate service facts"
  service_facts:
- name: "See the service <supervisord> facts as they are"
  debug:
    msg: "{{ansible_facts.services['supervisord.service'].state}}"
- name: "Verify if supervisord is running!"
  assert:
    that:
      - "'{{ansible_facts.services['supervisord.service'].state}}' == 'running'"
    fail_msg: "Supervisord is down."
    success_msg: "Supervisord is running."

