- name: "Populate service facts"
  ansible.builtin.service_facts:

- name: enable services on boot
  ansible.builtin.service:
     name: "{{ item }}"
     enabled: true
     state: started
  when: "item in services"
  with_items: '{{ services_on_boot }}'
